const ENV = import.meta.env
const { MODE, VITE_GLOB_API_URL, VITE_PORT, VITE_USE_MOCK, DEV, PROD, VITE_GLOB_APP_TITLE } = ENV

export { MODE, VITE_GLOB_API_URL, VITE_PORT, VITE_USE_MOCK, DEV, PROD, VITE_GLOB_APP_TITLE }
